### ISSUE TITLE
Replace all membership logos with SVG versions for clarity

### ISSUE THREAD

**Issue by ronaldtse** [CalConnect/calconnect.org#10]
<img width="591" alt="Screenshot 2024-12-03 at 6 42 20 PM" src="https://github.com/user-attachments/assets/3c8cf8f0-70c4-4da4-a228-e25623a1bc9c">

Rather pixellated now.

**Comment by MuhammadAhsan252** [comment]
@ronaldtse Do we have the svg version of logos?

**Comment by ronaldtse** [comment]
It’s easy to find them online. Let me know if you can’t find a particular one.
